// AUTO-GENERATED FILE. DO NOT MODIFY.

// This class was automatically generated by the MyDataBase tool
// from R.java. It should not be modified by hand.

unit Rjava;

{$mode objfpc}{$H+}
{$modeswitch unicodestrings}
{$namespace #JavaPackageName#}

interface

type
  R = class
  public
    type
      attr = class
      end;
 
      drawable = class
      public
        const
          background = $7f020000;
          button = $7f020001;
          dialog = $7f020002;
          ic_launcher = $7f020003;
          listview = $7f020004;
          logo = $7f020005;
          menu = $7f020006;
      end;
 
      string_ = class
      public
        const
          app_name = $7f030000;
      end;
 
      style = class
      public
        const
          DefaultTheme = $7f040000;
          RoundedDialog = $7f040002;
          WBCustom = $7f040001;
      end;
 
  end;

implementation

end.
