// AUTO-GENERATED FILE. DO NOT MODIFY.

// This class was automatically generated by the DemoSQLite tool
// from R.java. It should not be modified by hand.

unit Rjava;

{$mode objfpc}{$H+}
{$modeswitch unicodestrings}
{$namespace zeljus.com.demosqlite}

interface

type
  R = class
  public
    type
      attr = class
      end;
 
      drawable = class
      public
        const
          about = $7f020000;
          add_record = $7f020001;
          addrecord = $7f020002;
          apply_database = $7f020003;
          bluetooth_off = $7f020004;
          bluetooth_on = $7f020005;
          data_synchronization = $7f020006;
          data_transmission = $7f020007;
          delete_record = $7f020008;
          document = $7f020009;
          exit = $7f02000a;
          ic_launcher = $7f02000b;
          logo = $7f02000c;
          mail = $7f02000d;
          notes = $7f02000e;
          print = $7f02000f;
          rfid = $7f020010;
          settings = $7f020011;
          sum = $7f020012;
          tools = $7f020013;
      end;
 
      string_ = class
      public
        const
          app_name = $7f030000;
      end;
 
      style = class
      public
        const
          DefaultTheme = $7f040000;
      end;
 
  end;

implementation

end.
