// AUTO-GENERATED FILE. DO NOT MODIFY.

// This class was automatically generated by the SecondActivity tool
// from R.java. It should not be modified by hand.

unit Rjava;

{$mode objfpc}{$H+}
{$modeswitch unicodestrings}
{$namespace zeljus.com.secondactivity}

interface

type
  R = class
  public
    type
      attr = class
      end;
 
      color = class
      public
        const
          BackgroudnColor01 = $7f040000;
          BackgroudnColor03 = $7f040007;
          BackgroundColor02 = $7f040004;
          BackgroundColor04 = $7f04000c;
          BackgroundEditColor04 = $7f04000b;
          BackgroundPressColor02 = $7f040003;
          LineColor02 = $7f040006;
          LineColor04 = $7f04000e;
          LineEditColor04 = $7f04000d;
          LinePressColor02 = $7f040005;
          TextColor01 = $7f040001;
          TextColor02 = $7f040002;
          TextColor03 = $7f040008;
          TextColor04 = $7f04000a;
          messageTextColor03 = $7f040009;
      end;
 
      drawable = class
      public
        const
          background = $7f020000;
          button = $7f020001;
          dialog = $7f020002;
          edittext = $7f020003;
          ic_add = $7f020004;
          ic_firstrecord = $7f020005;
          ic_lastrecor = $7f020006;
          ic_launcher = $7f020007;
          ic_menu = $7f020008;
          ic_next = $7f020009;
          logo = $7f02000a;
          menu = $7f02000b;
          toast_drawable = $7f02000c;
      end;
 
      string_ = class
      public
        const
          app_name = $7f030000;
      end;
 
      style = class
      public
        const
          AlertDialog = $7f050002;
          CustomButton = $7f050001;
          DefaultTheme = $7f050000;
          EditText = $7f050003;
      end;
 
  end;

implementation

end.
