// AUTO-GENERATED FILE. DO NOT MODIFY.

// This class was automatically generated by the PandroidRadiPlayer tool
// from R.java. It should not be modified by hand.

unit Rjava;

{$mode objfpc}{$H+}
{$modeswitch unicodestrings}
{$namespace zeljus.com.pandroidradiplayer}

interface

type
  R = class
  public
    type
      attr = class
      end;
 
      drawable = class
      public
        const
          add_record = $7f020000;
          apply_database = $7f020001;
          chart = $7f020002;
          document = $7f020003;
          exit = $7f020004;
          first_record = $7f020005;
          go_forward = $7f020006;
          ic_launcher = $7f020007;
          last_record = $7f020008;
          logo = $7f020009;
          notes = $7f02000a;
          remote_database = $7f02000b;
          settings = $7f02000c;
          tools = $7f02000d;
      end;
 
      string_ = class
      public
        const
          app_name = $7f030000;
      end;
 
      style = class
      public
        const
          DefaultTheme = $7f040000;
      end;
 
  end;

implementation

end.
